"""
Report Service for LexGuard AI
Generates downloadable PDF reports for legal document analysis.
Uses reportlab for PDF generation. Falls back gracefully if not installed.
"""
import os
import traceback


class ReportService:
    def generate_document_report(
        self,
        doc_name: str,
        analysis_data: dict,
        clauses: list,
        output_path: str,
        user_details: dict = None,
    ) -> str:
        """Generate a professional PDF report."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            )
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors
            from reportlab.lib.units import inch
        except ImportError:
            raise RuntimeError(
                "reportlab is required for PDF export. "
                "Install it: pip install reportlab"
            )

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        styles = getSampleStyleSheet()
        story = []

        # Custom styles
        title_style = ParagraphStyle(
            'LexTitle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor=colors.HexColor("#001F3F"),
            spaceAfter=16,
        )
        subtitle_style = ParagraphStyle(
            'LexSubtitle',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=10,
        )
        body_style = ParagraphStyle(
            'LexBody',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor("#1e293b"),
        )

        # ── Title ──
        story.append(Paragraph("LexGuard AI — Legal Analysis Report", title_style))
        story.append(Paragraph(f"Document: {doc_name}", subtitle_style))
        story.append(Spacer(1, 16))

        # ── Risk Summary ──
        risk_level = analysis_data.get('risk_level', 'Medium')
        risk_score = analysis_data.get('risk_score', 0)
        risk_color_map = {'High': '#EF4444', 'Medium': '#F59E0B', 'Low': '#22C55E'}
        risk_color = risk_color_map.get(risk_level, '#64748b')

        risk_style = ParagraphStyle(
            'RiskStyle',
            parent=styles['Normal'],
            fontSize=16,
            textColor=colors.HexColor(risk_color),
            fontWeight='bold',
            spaceAfter=12,
        )
        story.append(Paragraph(f"Overall Risk: {risk_level} — Score: {risk_score}/100", risk_style))
        story.append(Spacer(1, 12))

        # ── Executive Summary ──
        summary = analysis_data.get('summary', 'No summary available.')
        if summary:
            story.append(Paragraph("Executive Summary", subtitle_style))
            story.append(Paragraph(summary, body_style))
            story.append(Spacer(1, 12))

        # ── Parties ──
        parties = analysis_data.get('parties') or []
        if parties:
            story.append(Paragraph("Involved Parties", subtitle_style))
            for p in parties:
                story.append(Paragraph(f"• {p}", body_style))
            story.append(Spacer(1, 12))

        # ── Recommendations ──
        recs = analysis_data.get('recommendations') or []
        if recs:
            story.append(Paragraph("AI Recommendations", subtitle_style))
            for rec in recs:
                story.append(Paragraph(f"• {rec}", body_style))
            story.append(Spacer(1, 12))

        # ── Key Clauses ──
        if clauses:
            story.append(Paragraph("Key Clauses Analyzed", subtitle_style))
            for clause in clauses:
                title = clause.get('title', 'Untitled')
                level = clause.get('risk_level', 'Low')
                summary_text = clause.get('summary', '')
                story.append(Paragraph(
                    f"<b>{title}</b> — <font color='{risk_color_map.get(level, '#64748b')}'>"
                    f"{level} Risk</font>",
                    body_style,
                ))
                if summary_text:
                    story.append(Paragraph(summary_text, body_style))
                story.append(Spacer(1, 6))

        # ── Footer ──
        story.append(Spacer(1, 24))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.HexColor("#94a3b8"),
        )
        story.append(Paragraph(
            "Generated by LexGuard AI — AI-powered legal document analysis. "
            "This report is for informational purposes only and does not constitute legal advice.",
            footer_style,
        ))

        doc.build(story)
        return output_path

    def _render_text_report(self, doc_name: str, analysis_data: dict, clauses: list, user_details: dict) -> str:
        lines = [
            "LexGuard AI — Legal Analysis Report",
            f"Document: {doc_name}",
            "",
        ]

        if user_details:
            if user_details.get("name"):
                lines.append(f"Prepared For: {user_details.get('name')}")
            if user_details.get("email"):
                lines.append(f"Email: {user_details.get('email')}")
            lines.append("")

        lines.append(f"Overall Risk: {analysis_data.get('risk_level', 'Medium')} — Score: {analysis_data.get('risk_score', 0)}/100")
        lines.append("")
        lines.append("Executive Summary:")
        lines.append(analysis_data.get('summary', 'No summary available.'))
        lines.append("")

        parties = analysis_data.get('parties') or []
        if parties:
            lines.append("Involved Parties:")
            for p in parties:
                lines.append(f"- {p}")
            lines.append("")

        recs = analysis_data.get('recommendations') or []
        if recs:
            lines.append("AI Recommendations:")
            for rec in recs:
                lines.append(f"- {rec}")
            lines.append("")

        if clauses:
            lines.append("Key Clauses Analyzed:")
            for clause in clauses:
                lines.append(f"* {clause.get('title', 'Untitled')} ({clause.get('risk_level', 'Low')} Risk)")
                if clause.get('summary'):
                    lines.append(f"  {clause.get('summary')}")
                lines.append("")

        lines.append("Generated by LexGuard AI — informational purposes only.")
        return "\n".join(lines)

    def generate_document_report_text(
        self,
        doc_name: str,
        analysis_data: dict,
        clauses: list,
        output_path: str,
        user_details: dict = None,
    ) -> str:
        content = self._render_text_report(doc_name, analysis_data, clauses, user_details)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return output_path

    def generate_document_report_json(
        self,
        doc_name: str,
        analysis_data: dict,
        clauses: list,
        output_path: str,
        user_details: dict = None,
    ) -> str:
        import json
        payload = {
            "document": {
                "name": doc_name,
                "user": user_details or {},
                "analysis": analysis_data,
                "clauses": clauses,
            }
        }
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        return output_path

    def generate_document_report_markdown(
        self,
        doc_name: str,
        analysis_data: dict,
        clauses: list,
        output_path: str,
        user_details: dict = None,
    ) -> str:
        lines = [
            "# LexGuard AI — Legal Analysis Report",
            f"**Document:** {doc_name}",
            "",
        ]
        if user_details:
            if user_details.get("name"):
                lines.append(f"**Prepared For:** {user_details.get('name')}")
            if user_details.get("email"):
                lines.append(f"**Email:** {user_details.get('email')}")
            lines.append("")

        lines.append(f"## Overall Risk: {analysis_data.get('risk_level', 'Medium')} — Score: {analysis_data.get('risk_score', 0)}/100")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append(analysis_data.get('summary', 'No summary available.'))
        lines.append("")

        parties = analysis_data.get('parties') or []
        if parties:
            lines.append("## Involved Parties")
            for p in parties:
                lines.append(f"- {p}")
            lines.append("")

        recs = analysis_data.get('recommendations') or []
        if recs:
            lines.append("## AI Recommendations")
            for rec in recs:
                lines.append(f"- {rec}")
            lines.append("")

        if clauses:
            lines.append("## Key Clauses Analyzed")
            for clause in clauses:
                lines.append(f"### {clause.get('title', 'Untitled')} ({clause.get('risk_level', 'Low')} Risk)")
                if clause.get('summary'):
                    lines.append(clause.get('summary'))
                lines.append("")

        lines.append("*Generated by LexGuard AI — informational purposes only.*")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return output_path

    def generate_document_report_docx(
        self,
        doc_name: str,
        analysis_data: dict,
        clauses: list,
        output_path: str,
        user_details: dict = None,
    ) -> str:
        try:
            import docx
        except ImportError:
            raise RuntimeError(
                "python-docx is required for DOCX export. "
                "Install it: pip install python-docx"
            )

        document = docx.Document()
        document.add_heading('LexGuard AI — Legal Analysis Report', level=1)
        document.add_paragraph(f'Document: {doc_name}')

        if user_details:
            if user_details.get('name'):
                document.add_paragraph(f"Prepared For: {user_details.get('name')}")
            if user_details.get('email'):
                document.add_paragraph(f"Email: {user_details.get('email')}")

        document.add_paragraph(f"Overall Risk: {analysis_data.get('risk_level', 'Medium')} — Score: {analysis_data.get('risk_score', 0)}/100")
        document.add_heading('Executive Summary', level=2)
        document.add_paragraph(analysis_data.get('summary', 'No summary available.'))

        parties = analysis_data.get('parties') or []
        if parties:
            document.add_heading('Involved Parties', level=2)
            for p in parties:
                document.add_paragraph(p, style='List Bullet')

        recs = analysis_data.get('recommendations') or []
        if recs:
            document.add_heading('AI Recommendations', level=2)
            for rec in recs:
                document.add_paragraph(rec, style='List Bullet')

        if clauses:
            document.add_heading('Key Clauses Analyzed', level=2)
            for clause in clauses:
                document.add_heading(clause.get('title', 'Untitled'), level=3)
                document.add_paragraph(f"Risk Level: {clause.get('risk_level', 'Low')}")
                if clause.get('summary'):
                    document.add_paragraph(clause.get('summary'))

        document.add_paragraph('Generated by LexGuard AI — informational purposes only.')
        document.save(output_path)
        return output_path


report_service = ReportService()
